SELECT * FROM USER_DATA;
SELECT * FROM USER_DATA_ROLES;
SELECT * FROM ROLE_DATA;
SELECT * FROM CLIMATE;
SELECT * FROM ITEM;
SELECT * FROM CATEGORY;
SELECT * FROM CLIMATE;
SELECT * FROM OCCASION ;
SELECT * FROM WIND;